### ISSUE TITLE
can not find the 'auto'

### ISSUE THREAD

**Issue by huiyongyong** [aysunrhn/Adaptive-Soft-Sensor-Design#2]

**Comment by aysunrhn** [comment]
Hi,

The `auto` function is available in the PLS toolbox. It simply scales your data and you can supply the mean and variance values for scaling. So you actually don't need the toolbox, you could write a small function that does the exact same thing. I used auto because I already had the toolbox.

Hope that helps, let me know if there's any other problem!

**Comment by huiyongyong** [comment]
thank you for you remind, 

Your excellent work has helped me a lot!



| |
hyylut
|
|
***@***.***
|
签名由网易邮箱大师定制
On 6/9/2021 20:16，Aysun ***@***.***> wrote：

Hi,

The auto function is available in the PLS toolbox. It simply scales your data and you can supply the mean and variance values for scaling. So you actually don't need the toolbox, you could write a small function that does the exact same thing. I used auto because I already had the toolbox.

Hope that helps, let me know if there's any other problem!

**Comment by huiyongyong** [comment]
| |
hyylut
|
|
***@***.***
|
签名由网易邮箱大师定制
On 6/9/2021 20:16，Aysun ***@***.***> wrote：

Hi,

The auto function is available in the PLS toolbox. It simply scales your data and you can supply the mean and variance values for scaling. So you actually don't need the toolbox, you could write a small function that does the exact same thing. I used auto because I already had the toolbox.

Hope that helps, let me know if there's any other problem!
